version: '3'
services:
  db_mongo:
    image: mongo:4.0
    restart: always
    env_file: .env
    volumes:
      - mongodb-data-volume:/db/data
      - ${MONGO_SCRIPTS_DIR}:/docker-entrypoint-initdb.d
    expose:
      - ${MONGO_PORT}
    ports: 
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - apinetwork
  api_graphql:
    build: 
      context: ./api-graphql
      dockerfile: Dockerfile 
    restart: always
    env_file: .env
    environment:
      API_PORT:   ${API_PORT}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_APP_USER: ${MONGO_APP_USER}
      MONGO_APP_PASS: ${MONGO_APP_PASS}
    ports: 
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db_mongo
    links:
      - db_mongo    
    networks:
      - apinetwork
volumes:
  mongodb-data-volume:
networks:
  apinetwork:
    driver: bridge